apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: livekit-hugging-voice
    newName: livekit-hugging-voice
    newTag: local
replicas:
  - name: hugging-voice
    count: 1
